version: "3"
services:
  bot:
    build:
      context: .
      dockerfile: ./bot/Dockerfile
    ports:
      - "43627:3000"
    volumes:
      - ".:/usr/src/app"
    env_file: ./bot/.env
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/slackus
      RUNNER_URL: http://runner:3000
    restart: always
  runner:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "33441:3000"
    env_file: ./runner/.env
    restart: always
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: slackus
    volumes:
      - "db_volume:/var/lib/postgresql/data"
volumes:
  db_volume: