version: "3"
services:
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    ports:
      - "43627:3000"
    volumes:
      - "./bot:/usr/src/app"
    env_file: .env
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/slackus
    restart: always
  runner:
    build:
      context: ./runner
      dockerfile: Dockerfile
    ports:
      - "33441:3000"
    volumes:
      - "./runner:/usr/src/app"
    env_file: .env
    restart: always
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: slackus
    volumes:
      - "db_volume:/var/lib/postgresql/data"
volumes:
  db_volume: